### PR TITLE
adding `toArray()`- and `sendNotifications()`-methods

### LINKED ISSUE #2: How to send notification to multiple devices
In the previous package, it was possible to provide an array of tokens and firebase would send a notification to each one, but in this package, it only allows to accept 1 token as a string and not an array.

[larafirebase](https://github.com/kutia-software-company/larafirebase)]

### PR DESCRIPTION
**Pull request by Maschga**
Hi,
I need a way to serialize the `Larafirebase` so I am able to store it in a database. However, I am not able not access the data due to the `private` fields.
Therefore, I added this `toArray()`-method.

I also added a `sendNotifications()`-method to fix #2.

It would be great, if you merge this PR.

Thank you very much for this project and your time!
~ Maschga

### CODE REVIEW

**Comment by Maschga** [comment]
Hi @gentritabazi , can you take a look at this pr? I don't have much time left to switch to the new Firebase API.

**Comment by gentritabazi** [comment]
Can you add documentation in readme for those changes

**Comment by Maschga** [comment]
> Can you add documentation in readme for those changes

I have done it. 👍

**Comment by gentritabazi** [comment]
@Maschga thanks for you contributions, I don't consider we need this change to be merged.

Multiple tokens is good to have, would be great if we can have specific PR for that.

**Pull request closed without merging**
